# Generated by Django 6.0.4 on 2026-08-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_roomtype_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cleaning_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
